### ISSUE TITLE
Solving environment: failed  ResolvePackageNotFound:

### ISSUE THREAD

**Issue by kingstontan** [vloison/Handwritten_Text_Recognition#1]
Hey, thanks for your work. I tried setting up the env using the commands provided but I'm getting the following error. 

I'm running Windows 10 and using PyCharm. Any pointers would be greatly appreciated. Cheers

![image](https://user-images.githubusercontent.com/42428153/96079002-4b170980-0ee6-11eb-94a1-d6608cb80f65.png)

**Comment by melohux** [comment]
The version of installed Anaconda should be >= 4.7.10. Hope this will help.

**Comment by kingstontan** [comment]
I fixed it by manually creating my own env. Thanks
