### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/media/vn_nguyen/hdd/hux/Results/10-15_21:46:45' when making predictions

### ISSUE THREAD

**Issue by kingstontan** [vloison/Handwritten_Text_Recognition#2]
I'm trying to make predictions on my own unlabelled dataset using this command:
`python line_predictor.py --data_path images/ --model_path trained_networks/ICFHR2014_model_imgH64.pth --imgH 89`

But I'm getting this error
`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/media/vn_nguyen/hdd/hux/Results/10-15_21:46:45'
`
![image](https://user-images.githubusercontent.com/42428153/96137923-d1a40900-0f2f-11eb-95d6-035fe2470881.png)

Any help would be greatly appreciated. Cheers

**Comment by melohux** [comment]
Sorry for this problem. Add the argument `--save_model_path path` in command line with your own path should be helpful. We will fix it soon.

**Comment by kingstontan** [comment]
thanks for your reply. I added the argument but it was still throwing me the same error, it only got fixed when i removed `self.time` .

![image](https://user-images.githubusercontent.com/42428153/96156074-3fa5fb80-0f43-11eb-8083-ea4c32e0b476.png)
