### ISSUE TITLE
variable "icdict" in line_predictor.py can't be resolved

### ISSUE THREAD

**Issue by kingstontan** [vloison/Handwritten_Text_Recognition#3]
I know it's defined in params.py but it's not linked to this variable

![image](https://user-images.githubusercontent.com/42428153/96141801-f4d0b780-0f33-11eb-950f-9e93e48dedb2.png)

**Comment by melohux** [comment]
Sorry for this. Change it to `params.icdict` will work. This will be fixed soon.

**Comment by kingstontan** [comment]
got it, thanks a bunch
